let currentList = [
    "At Two Thirty",
    "Autumn Fairy Tale",
    "Blood 13",
    "Crazy Alien 2019",
    "Cyan Wizard",
    "Deception Of The Novelist",
    "Devil's Vindate",
    "Fall in Love at First Kiss",
    "Forgetting Space",
    "Ghost Sword",
    "Girl Dorm",
    "Invincible Dragon",
    "Ip Man Legacy: Master Z",
    "Last Sunrise",
    "Love in 50 Meters",
    "Love The Way You Are",
    "Midnight Melody",
    "My Best Summer",
    "Neighbour",
    "Peak Rescue",
    "Seven Fright Nights",
    "Shanghai Fortress",
    "Silence Snow",
    "So Long, My Son",
    "Song of Youth",
    "The Big Shot",
    "The Business Strom of Ruhai",
    "The Demons Strike BaiYu Town 2",
    "The Human Comedy",
    "The Knight of Shadows Between Yin and Yang",
    "The New King of Comedy ",
    "The Real Iron Monkey",
    "The Rookies",
    "The Seven Sword",
    "The Shadow Play",
    "The Voice Unseen",
    "The Void Evidence",
    "The Wandering Earth",
    "Think Big Big",
    "Triple Threat",
    "Unforgivable Sin",
    "We Are Legends",
]

module.exports = currentList;